spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: sachinkapkoti1234@gmail.com
    password: Sacchu@242117
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

email:
  to: sachinkapkoti6789@gmail.com
  cc: sachinkapkoti6789@gmail.com
  subject: Test mail
  body:  "Hello Sachin, this is a test mail"