spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sachinkapkoti1234@gmail.com
    password: zqepqyadjygpmmjb
    protocol: smtp
    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true


email:
  to: advaitpro@gmail.com
  cc: sachinkapkoti1234@gmail.com
  subject: Test mail
  body:  "Hello Advait, this is a test mail"

server:
  port: 8081